### ISSUE TITLE
"PyDIPjavaio unavailable" -- how to silence this warning if I don't want to install Java?

### ISSUE THREAD

**Issue by crisluengo** [DIPlib/diplib#106]
Say I don't want to bother installing Java, and I don't need to use Bio-Formats. But I do want to install PyDIP from PyPI rather than building it myself (it makes it easier to package Python code that depends on DIPlib that way).

This is the code in question:
```python
# Here we import PyDIPjavaio if it exists
hasDIPjavaio = False
if importlib.util.find_spec('.PyDIPjavaio', __name__) is not None:
    lib = None
    try:
        from . import loadjvm
        lib = loadjvm.load_jvm()
        from . import PyDIPjavaio as javaio
        ImageRead = javaio.ImageRead
        hasDIPjavaio = True
    except Exception as e:
        print("PyDIPjavaio unavailable:")
        print(e)
        if lib:
            print("\nload_jvm returned '" + lib + "'")
        else:
            print("\nlibjvm not found")
```

The diagnostic is very useful, it prevents people from being surprised at `dip.ImageRead` not reading a PNG file, for example, and it helps people on their way to get it all to work. But it would be great if there was a way to silence this warning, even if it requires setting a global variable before importing DIPlib. Could we make something like this work?
```python
no_DIPjavaio = True
import diplib as dip
```

**Comment by crisluengo** [comment]
This works to set a variable in the `dip` namespace before the code in `__init__` is run:
```python
import importlib.util
#import sys
dipspec = importlib.util.find_spec('diplib')
dip = importlib.util.module_from_spec(dipspec)
#sys.modules['dip'] = dip
dip.no_DIPjavaio = True
dipspec.loader.exec_module(dip)
```
The commented out lines appear in [the docs](https://docs.python.org/3/library/importlib.html?highlight=importlib#checking-if-a-module-can-be-imported), but don't seem necessary.

The only weird thing is that the line `from .PyDIP_bin import *` runs all of `__init__`, without this variable set, and then the rest of `__init__` continues running, with this variable set. Very weird!

**Comment by crisluengo** [comment]
That's brilliant!

**Comment by crisluengo** [comment]
What do you think?
https://github.com/DIPlib/diplib/commit/5215b47b0ce4b1cb88c0e4609e59ef20af8b10e9

This is the output for different failure modes:
```none
>>> b=dip.ImageRead('DIP.tif','bioformats')
If you were trying to read an image format supported by BioFormats, note that
DIPjavaio is unavailable because:
 - PyDIPjavaio was not included in the build of the package.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/diplib/__init__.py", line 152, in ImageRead
    return PyDIP_bin_ImageRead(*args, **kwargs)
RuntimeError: Invalid flag: bioformats
in function: dip::FileInformation dip::ImageRead(dip::Image &, const dip::String &, dip::String) (/Users/cris/newdip/include/diplib/simple_file_io.h at line number 107)
>>>
```

```none
>>> b=dip.ImageRead('DIP.tif','bioformats')
If you were trying to read an image format supported by BioFormats, note that
DIPjavaio is unavailable because:
 - Failing to load JVM on purpose for testing
libjvm not found

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/diplib/__init__.py", line 152, in ImageRead
    return PyDIP_bin_ImageRead(*args, **kwargs)
RuntimeError: Invalid flag: bioformats
in function: dip::FileInformation dip::ImageRead(dip::Image&, const String&, dip::String) (/Users/cris/newdip/include/diplib/simple_file_io.h at line number 107)
>>>
```

```none
>>> b=dip.ImageRead('DIP.tif','bioformats')
If you were trying to read an image format supported by BioFormats, note that
DIPjavaio is unavailable because:
 - Failing to load JVM on purpose for testing
load_jvm returned '/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/lib/server/libjvm.dylib'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/diplib/__init__.py", line 152, in ImageRead
    return PyDIP_bin_ImageRead(*args, **kwargs)
RuntimeError: Invalid flag: bioformats
in function: dip::FileInformation dip::ImageRead(dip::Image&, const String&, dip::String) (/Users/cris/newdip/include/diplib/simple_file_io.h at line number 107)
>>>
```

**Comment by crisluengo** [comment]
I've added a descriptive help message.
de918438a27c9cdd5ff44f17ceec9d8354be506a

@wcaarls what do you think? Is this OK to push to the master branch?

**Comment by wcaarls** [comment]
Looks good to me, thanks!
