### ISSUE TITLE
No module named 'PyDIP.PyDIP_bin

### ISSUE THREAD

**Issue by TeddybearCrisis** [DIPlib/diplib#49]
I wanted to try some features of your lib but couldn't get it going following the instructions in the README. This appears to be a python sys.path issue since the installation procedure appears to work fine. I'd appreciate your help.

**Component**
PyDIP ([master@4cc96ca7](https://github.com/DIPlib/diplib/tree/4cc96ca7bb538652f54689e397259401b8aaee04))

**Bug Description**
Importing PyDIP raises "No module named 'PyDIP.PyDIP_bin'

**To Reproduce**
```
$ python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import sys; import pprint

>>> pprint.pprint(sys.path)
['',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/home/sgreve/.local/lib/python3.6/site-packages',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages']

>>> import PyDIP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/PyDIP/__init__.py", line 30, in <module>
    from PyDIP.PyDIP_bin import *
ModuleNotFoundError: No module named 'PyDIP.PyDIP_bin'
```

***Installation Procedure***
build and install from the cloned repo:
```
$ mkdir build && cd build && cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0

(shortened for readability)

~~~
-- Could NOT find FFTW3 (missing: FFTW3_INCLUDE_DIR FFTW3_LIBRARY_FFTW3F FFTW3_LIBRARY_FFTW3F_THREADS FFTW3_LIBRARY_FFTW3 FFTW3_LIBRARY_FFTW3_THREADS) 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY OPENGL_INCLUDE_DIR) 
-- Could NOT find FreeGLUT (missing: FREEGLUT_LIBRARY FREEGLUT_INCLUDE_DIR) 
-- FreeGLUT not found
-- Could NOT find GLFW (missing: GLFW_LIBRARY GLFW_INCLUDE_DIR) 
-- GLFW not found
-- pybind11 v2.4.2
-- Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR Matlab_MX_LIBRARY MAIN_PROGRAM) (found version "NOTFOUND")

--------------------------------------
   DIPlib CONFIGURATION REPORT

 * C++ compiler: GNU
 * C++ compiler flags:  -Wall -Wextra -Wconversion -Wsign-conversion -pedantic -Wno-unknown-pragmas -Wno-attributes -O3 -DNDEBUG
 * Build type: Release
 * Building shared library
 * Library installed to: /usr/local/lib
 * Binaries installed to: /usr/local/bin
 * Header files installed to: /usr/local/include
 * Doxygen documentation not configured
 * Using OpenMP for multithreading
 * Stack trace recording enabled
 * Asserts disabled
 * Unicode support enabled
 * Using 128-bit PRNG
 * ICS file IO enabled, with zlib
 * TIFF file IO enabled, with zlib, with JPEG
 * JPEG file IO enabled
 * Using built-in FFT
 * Unit test code included
 * DIPviewer module not configured
 * DIPviewer Java bindings not configured
 * DIPjavaio module added to 'all' target with interfaces: 
 * PyDIP module added to 'all' target
 * PyDIP compiled for Python version 3.7.5
 * PyDIP installed to: /usr/lib/python3/dist-packages/PyDIP
 * PyDIP uses the absolute path to DIPlib
 * DIPimage toolbox not configured

Next, type 'make; make check; make install'

--------------------------------------

-- Configuring done
-- Generating done
-- Build files have been written to: /home/sgreve/Projects/diplib/build

$ make && sudo make install
```

After those steps running through without errors the binaries and python modules look fine to me:
```
$ ls -la /usr/local/lib/*DIP*
-rw-r--r-- 1 root root     2772 Dez  9 18:12 /usr/local/lib/DIPjavaio.jar
-rw-r--r-- 1 root root    81528 Dez  9 18:14 /usr/local/lib/libDIPjavaio.so
-rw-r--r-- 1 root root 14651040 Dez  9 18:14 /usr/local/lib/libDIP.so

$ ls -la /usr/lib/python3/dist-packages/PyDIP
total 1932
drwxr-xr-x   2 root root    4096 Dez  9 18:16 .
drwxr-xr-x 123 root root   12288 Dez  3 20:19 ..
-rw-r--r--   1 root root    1542 Dez  9 18:09 __init__.py
-rw-r--r--   1 root root 1862344 Dez  9 18:15 PyDIP_bin.cpython-37m-x86_64-linux-gnu.so
-rw-r--r--   1 root root   85128 Dez  9 18:14 PyDIPjavaio.cpython-37m-x86_64-linux-gnu.so
-rw-r--r--   1 root root    6795 Dez  9 17:34 PyDIP_py.py
```

**System information:**
 - Ubuntu 18.04 (in Virtualbox on a Win 10 host)
 - Python 3.6.8
 - No Matlab
 - GCC 7.4.0

**Comment by slokhorst** [comment]
You are using Python 3.6 but PyDIP was built for Python 3.7 (note `PyDIP compiled for Python version 3.7.5`).

**Comment by TeddybearCrisis** [comment]
Thanks for the hint .. I'll try it with python 3.7. Did I miss that info in the docs?

**Comment by slokhorst** [comment]
No, but the python module has to be built with the same python version as the one it is going to be used with.

Can you try this (first delete the `build` directory)?
```bash
mkdir build && cd build
cmake -DPYBIND11_PYTHON_VERSION=3.6 ..
```

If it now says "PyDIP compiled for Python version **3.6.x**" you should be good and can follow the rest of the compilation steps in the regular way.

**Comment by TeddybearCrisis** [comment]
That's it - I feel a little stupid for not noticing. The bug is me. ;-)
Thanks for the help.

**Comment by slokhorst** [comment]
No problem. Happy you got it to work! :)
